services:

  backend:
    container_name: smarttimebackend
    build: ./backend
    restart: always
    ports:
      - "8020:8000"
    depends_on:
      - postgres
    networks:
      - ntanet

  frontend:
    container_name: smarttimefront
    build: ./frontend
    restart: always
    networks:
      - ntanet

  postgres:
  image: postgres:15
  environment:
    POSTGRES_USER: smarttime
    POSTGRES_PASSWORD: Nth1234
    POSTGRES_DB: smarttimedb
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
    - ntanet

volumes:
  postgres_data:

networks:
  ntanet:
    driver: bridge
