# Generated by Django 5.2.13 on 2026-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('slot_type', models.CharField(choices=[('STUDY', 'Étude'), ('BREAK', 'Pause'), ('COURSE', 'Cours Fixe'), ('PERSONAL', 'Personnel')], default='STUDY', max_length=20)),
                ('is_auto_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
